// ── Inventory data source ──────────────────────────────────────────────
// Real stock for Avto Plac Dado, scraped from the dealership's reklama5.mk
// listings (seller "Dragan", phone 071 394 113) and translated to English.
// Photos live in /public/cars/<id>/NN.jpg. Regenerate with scripts/gen-cars.cjs.

export type Fuel = "Petrol" | "Diesel" | "Hybrid" | "Electric";
export type Transmission = "Manual" | "Automatic";
export type Body =
  | "Hatchback"
  | "Sedan"
  | "SUV"
  | "Estate"
  | "Coupé"
  | "MPV";

export type Car = {
  id: string; // url slug, e.g. "bmw-318-2008"
  adId: string; // source reklama5 ad id
  name: string; // full display name, e.g. "BMW 318"
  make: string; // brand, e.g. "BMW"
  brandSlug: string; // logo file slug, e.g. "bmw"
  model: string; // model only, e.g. "318"
  price: number; // €
  year: number;
  mileage: number; // km
  fuel: Fuel;
  transmission: Transmission;
  body: Body;
  power: string; // e.g. "90 kW / 122 hp"
  hp: number; // horsepower (for sorting/display)
  color: string; // English colour name
  euro: string; // emission class, e.g. "Euro 5"
  registration: string; // e.g. "Macedonian, registered until 02.2026"
  rating: number; // 0–5 (derived)
  features: string[]; // English equipment list
  description: string; // English narrative
  images: string[]; // gallery, /public paths
  image: string; // first image (card thumbnail)
};

// Brand meta — logo slug + optical scale (measured once per PNG).
export const BRAND_META: Record<string, { name: string; scale: number }> = {
  peugeot: { name: "Peugeot", scale: 1.39 },
  hyundai: { name: "Hyundai", scale: 1.12 },
  renault: { name: "Renault", scale: 1.17 },
  audi: { name: "Audi", scale: 1 },
  citroen: { name: "Citroën", scale: 0.98 },
  fiat: { name: "Fiat", scale: 1.6 },
  opel: { name: "Opel", scale: 1.6 },
  seat: { name: "Seat", scale: 1 },
  nissan: { name: "Nissan", scale: 1.14 },
  volkswagen: { name: "Volkswagen", scale: 1.15 },
  mazda: { name: "Mazda", scale: 1 },
  dacia: { name: "Dacia", scale: 1.53 },
  bmw: { name: "BMW", scale: 0.98 },
  lancia: { name: "Lancia", scale: 1.6 },
  chevrolet: { name: "Chevrolet", scale: 1.05 },
  kia: { name: "Kia", scale: 1.31 },
  ford: { name: "Ford", scale: 1.01 },
  suzuki: { name: "Suzuki", scale: 1 },
};

export const BODIES: Body[] = [
  "Hatchback",
  "Sedan",
  "SUV",
  "Estate",
  "Coupé",
  "MPV",
];

export const CARS: Car[] = [
  {
    id: "renault-laguna-2011",
    adId: "5222133",
    name: "Renault Laguna",
    make: "Renault",
    brandSlug: "renault",
    model: "Laguna",
    price: 4999,
    year: 2011,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Sedan",
    power: "81 kW / 110 hp",
    hp: 110,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 02.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Alloy wheels", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags", "Winter tyres"],
    description:
      "This 2011 Renault Laguna runs a 1.5-litre diesel engine producing 81 kW / 110 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/renault-laguna-2011/01.jpg", "/cars/renault-laguna-2011/02.jpg", "/cars/renault-laguna-2011/03.jpg", "/cars/renault-laguna-2011/04.jpg", "/cars/renault-laguna-2011/05.jpg", "/cars/renault-laguna-2011/06.jpg", "/cars/renault-laguna-2011/07.jpg", "/cars/renault-laguna-2011/08.jpg", "/cars/renault-laguna-2011/09.jpg"],
    image: "/cars/renault-laguna-2011/01.jpg",
  },
  {
    id: "audi-a3-2009",
    adId: "5385018",
    name: "Audi A3",
    make: "Audi",
    brandSlug: "audi",
    model: "A3",
    price: 6499,
    year: 2009,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "103 kW / 140 hp",
    hp: 140,
    color: "Black",
    euro: "Euro 5",
    registration: "Macedonian, registered until 01.2026",
    rating: 4.2,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Fog lights", "Alloy wheels", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags"],
    description:
      "This 2009 Audi A3 runs a 2.0-litre diesel engine producing 103 kW / 140 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/audi-a3-2009/01.jpg", "/cars/audi-a3-2009/02.jpg", "/cars/audi-a3-2009/03.jpg", "/cars/audi-a3-2009/04.jpg", "/cars/audi-a3-2009/05.jpg", "/cars/audi-a3-2009/06.jpg", "/cars/audi-a3-2009/07.jpg", "/cars/audi-a3-2009/08.jpg", "/cars/audi-a3-2009/09.jpg"],
    image: "/cars/audi-a3-2009/01.jpg",
  },
  {
    id: "lancia-delta-2009",
    adId: "5448156",
    name: "Lancia Delta",
    make: "Lancia",
    brandSlug: "lancia",
    model: "Delta",
    price: 5250,
    year: 2009,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "88 kW / 120 hp",
    hp: 120,
    color: "Blue",
    euro: "Euro 5",
    registration: "Macedonian, registered until 02.2026",
    rating: 4.2,
    features: ["Air conditioning", "Trip computer", "Fog lights", "Alloy wheels", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2009 Lancia Delta runs a 1.6-litre diesel engine producing 88 kW / 120 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia, Finished in blue, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/lancia-delta-2009/01.jpg", "/cars/lancia-delta-2009/02.jpg", "/cars/lancia-delta-2009/03.jpg", "/cars/lancia-delta-2009/04.jpg", "/cars/lancia-delta-2009/05.jpg", "/cars/lancia-delta-2009/06.jpg", "/cars/lancia-delta-2009/07.jpg", "/cars/lancia-delta-2009/08.jpg", "/cars/lancia-delta-2009/09.jpg", "/cars/lancia-delta-2009/10.jpg"],
    image: "/cars/lancia-delta-2009/01.jpg",
  },
  {
    id: "renault-twingo-2013",
    adId: "5600973",
    name: "Renault Twingo",
    make: "Renault",
    brandSlug: "renault",
    model: "Twingo",
    price: 3999,
    year: 2013,
    mileage: 180000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "55 kW / 75 hp",
    hp: 75,
    color: "White",
    euro: "Euro 5",
    registration: "Macedonian, registered until 12.2024",
    rating: 4.3,
    features: ["Air conditioning", "Trip computer", "Fog lights", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "Winter tyres"],
    description:
      "This 2013 Renault Twingo runs a 1.2-litre petrol engine producing 55 kW / 75 hp, paired with a manual gearbox, and has covered 180,000 km. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/renault-twingo-2013/01.jpg", "/cars/renault-twingo-2013/02.jpg", "/cars/renault-twingo-2013/03.jpg", "/cars/renault-twingo-2013/04.jpg", "/cars/renault-twingo-2013/05.jpg", "/cars/renault-twingo-2013/06.jpg", "/cars/renault-twingo-2013/07.jpg", "/cars/renault-twingo-2013/08.jpg", "/cars/renault-twingo-2013/09.jpg", "/cars/renault-twingo-2013/10.jpg"],
    image: "/cars/renault-twingo-2013/01.jpg",
  },
  {
    id: "renault-megane-2012",
    adId: "5606998",
    name: "Renault Megane",
    make: "Renault",
    brandSlug: "renault",
    model: "Megane",
    price: 5200,
    year: 2012,
    mileage: 190000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "66 kW / 90 hp",
    hp: 90,
    color: "White",
    euro: "Euro 5",
    registration: "Macedonian, registered until 01.2026",
    rating: 4.3,
    features: ["Air conditioning", "Trip computer", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "Winter tyres"],
    description:
      "This 2012 Renault Megane runs a 1.5-litre diesel engine producing 66 kW / 90 hp, paired with a manual gearbox, and has covered 190,000 km. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/renault-megane-2012/01.jpg", "/cars/renault-megane-2012/02.jpg", "/cars/renault-megane-2012/03.jpg", "/cars/renault-megane-2012/04.jpg", "/cars/renault-megane-2012/05.jpg", "/cars/renault-megane-2012/06.jpg", "/cars/renault-megane-2012/07.jpg", "/cars/renault-megane-2012/08.jpg", "/cars/renault-megane-2012/09.jpg"],
    image: "/cars/renault-megane-2012/01.jpg",
  },
  {
    id: "seat-alhambra-2010",
    adId: "5614394",
    name: "Seat Alhambra",
    make: "Seat",
    brandSlug: "seat",
    model: "Alhambra",
    price: 6999,
    year: 2010,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "MPV",
    power: "103 kW / 140 hp",
    hp: 140,
    color: "Blue",
    euro: "Euro 4",
    registration: "Macedonian, registered until 05.2026",
    rating: 4.2,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Heated seats", "Alloy wheels", "DVD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "Certified tow bar", "Tow bar", "Tinted rear windows"],
    description:
      "This 2010 Seat Alhambra runs a 2.0-litre diesel engine producing 103 kW / 140 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in blue, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/seat-alhambra-2010/01.jpg", "/cars/seat-alhambra-2010/02.jpg", "/cars/seat-alhambra-2010/03.jpg", "/cars/seat-alhambra-2010/04.jpg", "/cars/seat-alhambra-2010/05.jpg", "/cars/seat-alhambra-2010/06.jpg", "/cars/seat-alhambra-2010/07.jpg", "/cars/seat-alhambra-2010/08.jpg", "/cars/seat-alhambra-2010/09.jpg", "/cars/seat-alhambra-2010/10.jpg"],
    image: "/cars/seat-alhambra-2010/01.jpg",
  },
  {
    id: "bmw-318-2008",
    adId: "5644904",
    name: "BMW 318",
    make: "BMW",
    brandSlug: "bmw",
    model: "318",
    price: 6499,
    year: 2008,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Sedan",
    power: "90 kW / 122 hp",
    hp: 122,
    color: "Blue",
    euro: "Euro 5",
    registration: "Macedonian, registered until 02.2026",
    rating: 4.2,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Xenon headlights", "Fog lights", "Heated seats", "Alloy wheels", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS & ESP", "ABS", "ESP", "Winter tyres"],
    description:
      "This 2008 BMW 318 runs a diesel engine producing 90 kW / 122 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in blue, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/bmw-318-2008/01.jpg", "/cars/bmw-318-2008/02.jpg", "/cars/bmw-318-2008/03.jpg", "/cars/bmw-318-2008/04.jpg", "/cars/bmw-318-2008/05.jpg", "/cars/bmw-318-2008/06.jpg", "/cars/bmw-318-2008/07.jpg", "/cars/bmw-318-2008/08.jpg", "/cars/bmw-318-2008/09.jpg", "/cars/bmw-318-2008/10.jpg"],
    image: "/cars/bmw-318-2008/01.jpg",
  },
  {
    id: "chevrolet-spark-2012",
    adId: "5654817",
    name: "Chevrolet Spark",
    make: "Chevrolet",
    brandSlug: "chevrolet",
    model: "Spark",
    price: 3999,
    year: 2012,
    mileage: 170000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "50 kW / 68 hp",
    hp: 68,
    color: "Red",
    euro: "Euro 5",
    registration: "Macedonian, registered until 02.2026",
    rating: 4.3,
    features: ["Air conditioning", "Trip computer", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2012 Chevrolet Spark runs a 1.0-litre petrol engine producing 50 kW / 68 hp, paired with a manual gearbox, and has covered 170,000 km with full service history. Imported from Slovenia, Finished in red, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/chevrolet-spark-2012/01.jpg", "/cars/chevrolet-spark-2012/02.jpg", "/cars/chevrolet-spark-2012/03.jpg", "/cars/chevrolet-spark-2012/04.jpg", "/cars/chevrolet-spark-2012/05.jpg", "/cars/chevrolet-spark-2012/06.jpg", "/cars/chevrolet-spark-2012/07.jpg", "/cars/chevrolet-spark-2012/08.jpg", "/cars/chevrolet-spark-2012/09.jpg"],
    image: "/cars/chevrolet-spark-2012/01.jpg",
  },
  {
    id: "ford-fiesta-2009",
    adId: "5668728",
    name: "Ford Fiesta",
    make: "Ford",
    brandSlug: "ford",
    model: "Fiesta",
    price: 4399,
    year: 2009,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "50 kW / 68 hp",
    hp: 68,
    color: "Yellow",
    euro: "Euro 4",
    registration: "Macedonian, registered until 03.2026",
    rating: 4.2,
    features: ["Climate control", "Air conditioning", "Trip computer", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "Winter tyres"],
    description:
      "This 2009 Ford Fiesta runs a 1.4-litre diesel engine producing 50 kW / 68 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia, Finished in yellow, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/ford-fiesta-2009/01.jpg", "/cars/ford-fiesta-2009/02.jpg", "/cars/ford-fiesta-2009/03.jpg", "/cars/ford-fiesta-2009/04.jpg", "/cars/ford-fiesta-2009/05.jpg", "/cars/ford-fiesta-2009/06.jpg", "/cars/ford-fiesta-2009/07.jpg", "/cars/ford-fiesta-2009/08.jpg", "/cars/ford-fiesta-2009/09.jpg"],
    image: "/cars/ford-fiesta-2009/01.jpg",
  },
  {
    id: "fiat-panda-2010",
    adId: "5685113",
    name: "Fiat Panda",
    make: "Fiat",
    brandSlug: "fiat",
    model: "Panda",
    price: 5200,
    year: 2010,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Hatchback",
    power: "50 kW / 68 hp",
    hp: 68,
    color: "Black",
    euro: "Euro 4",
    registration: "Macedonian, registered until 03.2026",
    rating: 4.2,
    features: ["Climate control", "Air conditioning", "Trip computer", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS"],
    description:
      "This 2010 Fiat Panda runs a 1.2-litre petrol engine producing 50 kW / 68 hp, paired with a automatic gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/fiat-panda-2010/01.jpg", "/cars/fiat-panda-2010/02.jpg", "/cars/fiat-panda-2010/03.jpg", "/cars/fiat-panda-2010/04.jpg", "/cars/fiat-panda-2010/05.jpg", "/cars/fiat-panda-2010/06.jpg", "/cars/fiat-panda-2010/07.jpg", "/cars/fiat-panda-2010/08.jpg", "/cars/fiat-panda-2010/09.jpg"],
    image: "/cars/fiat-panda-2010/01.jpg",
  },
  {
    id: "volkswagen-golf-2011",
    adId: "5690620",
    name: "Volkswagen Golf",
    make: "Volkswagen",
    brandSlug: "volkswagen",
    model: "Golf",
    price: 5700,
    year: 2011,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Estate",
    power: "77 kW / 105 hp",
    hp: 105,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 04.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Fog lights", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags"],
    description:
      "This 2011 Volkswagen Golf runs a 1.6-litre diesel engine producing 77 kW / 105 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/volkswagen-golf-2011/01.jpg", "/cars/volkswagen-golf-2011/02.jpg", "/cars/volkswagen-golf-2011/03.jpg", "/cars/volkswagen-golf-2011/04.jpg", "/cars/volkswagen-golf-2011/05.jpg", "/cars/volkswagen-golf-2011/06.jpg", "/cars/volkswagen-golf-2011/07.jpg", "/cars/volkswagen-golf-2011/08.jpg", "/cars/volkswagen-golf-2011/09.jpg", "/cars/volkswagen-golf-2011/10.jpg"],
    image: "/cars/volkswagen-golf-2011/01.jpg",
  },
  {
    id: "peugeot-208-2016",
    adId: "5703687",
    name: "Peugeot 208",
    make: "Peugeot",
    brandSlug: "peugeot",
    model: "208",
    price: 6500,
    year: 2016,
    mileage: 180000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "70 kW / 95 hp",
    hp: 95,
    color: "White",
    euro: "Euro 6",
    registration: "Macedonian, registered until 04.2026",
    rating: 4.4,
    features: ["Air conditioning", "Trip computer", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "ISOFIX", "AUX input", "USB"],
    description:
      "This 2016 Peugeot 208 runs a 1.6-litre diesel engine producing 70 kW / 95 hp, paired with a manual gearbox, and has covered 180,000 km with full service history. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 6 compliant.",
    images: ["/cars/peugeot-208-2016/01.jpg", "/cars/peugeot-208-2016/02.jpg", "/cars/peugeot-208-2016/03.jpg", "/cars/peugeot-208-2016/04.jpg", "/cars/peugeot-208-2016/05.jpg", "/cars/peugeot-208-2016/06.jpg", "/cars/peugeot-208-2016/07.jpg", "/cars/peugeot-208-2016/08.jpg", "/cars/peugeot-208-2016/09.jpg", "/cars/peugeot-208-2016/10.jpg", "/cars/peugeot-208-2016/11.jpg"],
    image: "/cars/peugeot-208-2016/01.jpg",
  },
  {
    id: "hyundai-i30-2014",
    adId: "5709337",
    name: "Hyundai i30",
    make: "Hyundai",
    brandSlug: "hyundai",
    model: "i30",
    price: 6950,
    year: 2014,
    mileage: 190000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "81 kW / 110 hp",
    hp: 110,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 04.2026",
    rating: 4.4,
    features: ["Climate control", "Air conditioning", "Trip computer", "Fog lights", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "ISOFIX", "AUX input", "USB"],
    description:
      "This 2014 Hyundai i30 runs a 1.6-litre diesel engine producing 81 kW / 110 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/hyundai-i30-2014/01.jpg", "/cars/hyundai-i30-2014/02.jpg", "/cars/hyundai-i30-2014/03.jpg", "/cars/hyundai-i30-2014/04.jpg", "/cars/hyundai-i30-2014/05.jpg", "/cars/hyundai-i30-2014/06.jpg", "/cars/hyundai-i30-2014/07.jpg", "/cars/hyundai-i30-2014/08.jpg", "/cars/hyundai-i30-2014/09.jpg"],
    image: "/cars/hyundai-i30-2014/01.jpg",
  },
  {
    id: "dacia-duster-2011",
    adId: "5725112",
    name: "Dacia Duster",
    make: "Dacia",
    brandSlug: "dacia",
    model: "Duster",
    price: 7250,
    year: 2011,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "SUV",
    power: "63 kW / 86 hp",
    hp: 86,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 04.2026",
    rating: 4.3,
    features: ["Air conditioning", "Trip computer", "Fog lights", "Alloy wheels", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2011 Dacia Duster runs a 1.5-litre diesel engine producing 63 kW / 86 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/dacia-duster-2011/01.jpg", "/cars/dacia-duster-2011/02.jpg", "/cars/dacia-duster-2011/03.jpg", "/cars/dacia-duster-2011/04.jpg", "/cars/dacia-duster-2011/05.jpg", "/cars/dacia-duster-2011/06.jpg", "/cars/dacia-duster-2011/07.jpg", "/cars/dacia-duster-2011/08.jpg", "/cars/dacia-duster-2011/09.jpg"],
    image: "/cars/dacia-duster-2011/01.jpg",
  },
  {
    id: "audi-a1-2015",
    adId: "5735069",
    name: "Audi A1",
    make: "Audi",
    brandSlug: "audi",
    model: "A1",
    price: 8499,
    year: 2015,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "66 kW / 90 hp",
    hp: 90,
    color: "Grey",
    euro: "Euro 6",
    registration: "Macedonian, registered until 05.2026",
    rating: 4.4,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Parking sensors", "Navigation", "Fog lights", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags"],
    description:
      "This 2015 Audi A1 runs a 1.6-litre diesel engine producing 66 kW / 90 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 6 compliant.",
    images: ["/cars/audi-a1-2015/01.jpg", "/cars/audi-a1-2015/02.jpg", "/cars/audi-a1-2015/03.jpg", "/cars/audi-a1-2015/04.jpg", "/cars/audi-a1-2015/05.jpg", "/cars/audi-a1-2015/06.jpg"],
    image: "/cars/audi-a1-2015/01.jpg",
  },
  {
    id: "seat-alhambra-2011",
    adId: "5743337",
    name: "Seat Alhambra",
    make: "Seat",
    brandSlug: "seat",
    model: "Alhambra",
    price: 6999,
    year: 2011,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "MPV",
    power: "85 kW / 116 hp",
    hp: 116,
    color: "Black",
    euro: "Euro 4",
    registration: "Macedonian, registered until 05.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Fog lights", "Alloy wheels", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags", "Tow bar", "ISOFIX", "USB"],
    description:
      "This 2011 Seat Alhambra runs a 1.9-litre diesel engine producing 85 kW / 116 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/seat-alhambra-2011/01.jpg", "/cars/seat-alhambra-2011/02.jpg", "/cars/seat-alhambra-2011/03.jpg", "/cars/seat-alhambra-2011/04.jpg", "/cars/seat-alhambra-2011/05.jpg", "/cars/seat-alhambra-2011/06.jpg"],
    image: "/cars/seat-alhambra-2011/01.jpg",
  },
  {
    id: "opel-corsa-2012",
    adId: "5752020",
    name: "Opel Corsa",
    make: "Opel",
    brandSlug: "opel",
    model: "Corsa",
    price: 5699,
    year: 2012,
    mileage: 140000,
    fuel: "Petrol",
    transmission: "Automatic",
    body: "Hatchback",
    power: "63 kW / 86 hp",
    hp: 86,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 05.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Alloy wheels", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2012 Opel Corsa runs a 1.2-litre petrol engine producing 63 kW / 86 hp, paired with an automatic gearbox, and has covered 140,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/opel-corsa-2012/01.jpg", "/cars/opel-corsa-2012/02.jpg", "/cars/opel-corsa-2012/03.jpg", "/cars/opel-corsa-2012/04.jpg", "/cars/opel-corsa-2012/05.jpg", "/cars/opel-corsa-2012/06.jpg", "/cars/opel-corsa-2012/07.jpg", "/cars/opel-corsa-2012/08.jpg", "/cars/opel-corsa-2012/09.jpg"],
    image: "/cars/opel-corsa-2012/01.jpg",
  },
  {
    id: "nissan-juke-2012",
    adId: "5758200",
    name: "Nissan Juke",
    make: "Nissan",
    brandSlug: "nissan",
    model: "Juke",
    price: 7650,
    year: 2012,
    mileage: 180000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "SUV",
    power: "81 kW / 110 hp",
    hp: 110,
    color: "White",
    euro: "Euro 5",
    registration: "Macedonian, registered until 06.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Navigation", "Fog lights", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2012 Nissan Juke runs a 1.5-litre diesel engine producing 81 kW / 110 hp, paired with a manual gearbox, and has covered 180,000 km with full service history. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/nissan-juke-2012/01.jpg", "/cars/nissan-juke-2012/02.jpg", "/cars/nissan-juke-2012/03.jpg", "/cars/nissan-juke-2012/04.jpg", "/cars/nissan-juke-2012/05.jpg", "/cars/nissan-juke-2012/06.jpg", "/cars/nissan-juke-2012/07.jpg", "/cars/nissan-juke-2012/08.jpg", "/cars/nissan-juke-2012/09.jpg"],
    image: "/cars/nissan-juke-2012/01.jpg",
  },
  {
    id: "peugeot-308-2015",
    adId: "5764350",
    name: "Peugeot 308",
    make: "Peugeot",
    brandSlug: "peugeot",
    model: "308",
    price: 7999,
    year: 2015,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "68 kW / 92 hp",
    hp: 92,
    color: "Brown",
    euro: "Euro 5",
    registration: "Macedonian, registered until 06.2026",
    rating: 4.4,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Parking sensors", "Xenon headlights", "Fog lights", "Alloy wheels", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags"],
    description:
      "This 2015 Peugeot 308 runs a 1.6-litre diesel engine producing 68 kW / 92 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in brown, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/peugeot-308-2015/01.jpg", "/cars/peugeot-308-2015/02.jpg", "/cars/peugeot-308-2015/03.jpg", "/cars/peugeot-308-2015/04.jpg", "/cars/peugeot-308-2015/05.jpg", "/cars/peugeot-308-2015/06.jpg", "/cars/peugeot-308-2015/07.jpg", "/cars/peugeot-308-2015/08.jpg", "/cars/peugeot-308-2015/09.jpg"],
    image: "/cars/peugeot-308-2015/01.jpg",
  },
  {
    id: "kia-rio-2013",
    adId: "5765404",
    name: "Kia Rio",
    make: "Kia",
    brandSlug: "kia",
    model: "Rio",
    price: 5200,
    year: 2013,
    mileage: 190000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "55 kW / 75 hp",
    hp: 75,
    color: "White",
    euro: "Euro 5",
    registration: "Macedonian, registered until 06.2026",
    rating: 4.3,
    features: ["Air conditioning", "Trip computer", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2013 Kia Rio runs a 1.1-litre diesel engine producing 55 kW / 75 hp, paired with a manual gearbox, and has covered 190,000 km. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/kia-rio-2013/01.jpg", "/cars/kia-rio-2013/02.jpg", "/cars/kia-rio-2013/03.jpg", "/cars/kia-rio-2013/04.jpg", "/cars/kia-rio-2013/05.jpg", "/cars/kia-rio-2013/06.jpg", "/cars/kia-rio-2013/07.jpg", "/cars/kia-rio-2013/08.jpg", "/cars/kia-rio-2013/09.jpg", "/cars/kia-rio-2013/10.jpg"],
    image: "/cars/kia-rio-2013/01.jpg",
  },
  {
    id: "nissan-micra-2009",
    adId: "5776079",
    name: "Nissan Micra",
    make: "Nissan",
    brandSlug: "nissan",
    model: "Micra",
    price: 3650,
    year: 2009,
    mileage: 170000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "59 kW / 80 hp",
    hp: 80,
    color: "Black",
    euro: "Euro 4",
    registration: "Macedonian, registered until 03.2027",
    rating: 4.2,
    features: ["Air conditioning", "CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "4 airbags", "Airbags"],
    description:
      "This 2009 Nissan Micra runs a 1.2-litre petrol engine producing 59 kW / 80 hp, paired with a manual gearbox, and has covered 170,000 km. Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/nissan-micra-2009/01.jpg", "/cars/nissan-micra-2009/02.jpg", "/cars/nissan-micra-2009/03.jpg", "/cars/nissan-micra-2009/04.jpg", "/cars/nissan-micra-2009/05.jpg", "/cars/nissan-micra-2009/06.jpg", "/cars/nissan-micra-2009/07.jpg", "/cars/nissan-micra-2009/08.jpg", "/cars/nissan-micra-2009/09.jpg"],
    image: "/cars/nissan-micra-2009/01.jpg",
  },
  {
    id: "audi-a1-2014",
    adId: "5781398",
    name: "Audi A1",
    make: "Audi",
    brandSlug: "audi",
    model: "A1",
    price: 8499,
    year: 2014,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "66 kW / 90 hp",
    hp: 90,
    color: "Black",
    euro: "Euro 5",
    registration: "Macedonian, registered until 06.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Parking sensors", "Navigation", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "Summer tyres"],
    description:
      "This 2014 Audi A1 runs a 1.6-litre diesel engine producing 66 kW / 90 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia, Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/audi-a1-2014/01.jpg", "/cars/audi-a1-2014/02.jpg", "/cars/audi-a1-2014/03.jpg", "/cars/audi-a1-2014/04.jpg", "/cars/audi-a1-2014/05.jpg", "/cars/audi-a1-2014/06.jpg", "/cars/audi-a1-2014/07.jpg", "/cars/audi-a1-2014/08.jpg", "/cars/audi-a1-2014/09.jpg", "/cars/audi-a1-2014/10.jpg"],
    image: "/cars/audi-a1-2014/01.jpg",
  },
  {
    id: "citroen-c4cactus-2015",
    adId: "5799027",
    name: "Citroën C4 Cactus",
    make: "Citroën",
    brandSlug: "citroen",
    model: "C4 Cactus",
    price: 7199,
    year: 2015,
    mileage: 180000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "60 kW / 82 hp",
    hp: 82,
    color: "Grey",
    euro: "Euro 6",
    registration: "Macedonian, registered until 07.2026",
    rating: 4.4,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Parking sensors", "Rear camera", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2015 Citroën C4 Cactus runs a 1.2-litre petrol engine producing 60 kW / 82 hp, paired with a manual gearbox, and has covered 180,000 km. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 6 compliant.",
    images: ["/cars/citroen-c4cactus-2015/01.jpg", "/cars/citroen-c4cactus-2015/02.jpg", "/cars/citroen-c4cactus-2015/03.jpg", "/cars/citroen-c4cactus-2015/04.jpg", "/cars/citroen-c4cactus-2015/05.jpg", "/cars/citroen-c4cactus-2015/06.jpg", "/cars/citroen-c4cactus-2015/07.jpg", "/cars/citroen-c4cactus-2015/08.jpg", "/cars/citroen-c4cactus-2015/09.jpg", "/cars/citroen-c4cactus-2015/10.jpg", "/cars/citroen-c4cactus-2015/11.jpg"],
    image: "/cars/citroen-c4cactus-2015/01.jpg",
  },
  {
    id: "fiat-punto-2011",
    adId: "5801076",
    name: "Fiat Punto",
    make: "Fiat",
    brandSlug: "fiat",
    model: "Punto",
    price: 4499,
    year: 2011,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "74 kW / 101 hp",
    hp: 101,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 07.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Fog lights", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2011 Fiat Punto runs a 1.4-litre petrol engine producing 74 kW / 101 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/fiat-punto-2011/01.jpg", "/cars/fiat-punto-2011/02.jpg", "/cars/fiat-punto-2011/03.jpg", "/cars/fiat-punto-2011/04.jpg", "/cars/fiat-punto-2011/05.jpg", "/cars/fiat-punto-2011/06.jpg", "/cars/fiat-punto-2011/07.jpg", "/cars/fiat-punto-2011/08.jpg", "/cars/fiat-punto-2011/09.jpg"],
    image: "/cars/fiat-punto-2011/01.jpg",
  },
  {
    id: "renault-clio-2007",
    adId: "5803287",
    name: "Renault Clio",
    make: "Renault",
    brandSlug: "renault",
    model: "Clio",
    price: 3350,
    year: 2007,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "55 kW / 75 hp",
    hp: 75,
    color: "Grey",
    euro: "Euro 4",
    registration: "Macedonian, registered until 08.2026",
    rating: 4.2,
    features: ["Air conditioning", "Trip computer", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags"],
    description:
      "This 2007 Renault Clio runs a 1.2-litre petrol engine producing 55 kW / 75 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/renault-clio-2007/01.jpg", "/cars/renault-clio-2007/02.jpg", "/cars/renault-clio-2007/03.jpg", "/cars/renault-clio-2007/04.jpg", "/cars/renault-clio-2007/05.jpg", "/cars/renault-clio-2007/06.jpg", "/cars/renault-clio-2007/07.jpg", "/cars/renault-clio-2007/08.jpg", "/cars/renault-clio-2007/09.jpg"],
    image: "/cars/renault-clio-2007/01.jpg",
  },
  {
    id: "hyundai-i20-2010",
    adId: "5809053",
    name: "Hyundai i20",
    make: "Hyundai",
    brandSlug: "hyundai",
    model: "i20",
    price: 3990,
    year: 2010,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "74 kW / 101 hp",
    hp: 101,
    color: "Brown",
    euro: "Euro 5",
    registration: "Macedonian, registered until 08.2026",
    rating: 4.2,
    features: ["Air conditioning", "Trip computer", "Alloy wheels", "Full service history", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "6 airbags", "Airbags", "ISOFIX", "AUX input", "USB", "Summer tyres"],
    description:
      "This 2010 Hyundai i20 runs a 1.4-litre petrol engine producing 74 kW / 101 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in brown, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/hyundai-i20-2010/01.jpg", "/cars/hyundai-i20-2010/02.jpg", "/cars/hyundai-i20-2010/03.jpg", "/cars/hyundai-i20-2010/04.jpg", "/cars/hyundai-i20-2010/05.jpg", "/cars/hyundai-i20-2010/06.jpg", "/cars/hyundai-i20-2010/07.jpg", "/cars/hyundai-i20-2010/08.jpg", "/cars/hyundai-i20-2010/09.jpg"],
    image: "/cars/hyundai-i20-2010/01.jpg",
  },
  {
    id: "hyundai-getz-2008",
    adId: "5817129",
    name: "Hyundai Getz",
    make: "Hyundai",
    brandSlug: "hyundai",
    model: "Getz",
    price: 3100,
    year: 2008,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "49 kW / 67 hp",
    hp: 67,
    color: "Red",
    euro: "Euro 4",
    registration: "Macedonian, registered until 08.2027",
    rating: 4.2,
    features: ["Air conditioning", "CD radio", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "4 airbags", "Airbags"],
    description:
      "This 2008 Hyundai Getz runs a 1.1-litre petrol engine producing 49 kW / 67 hp, paired with a manual gearbox, and has covered 190,000 km. Imported from Slovenia, Finished in red, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/hyundai-getz-2008/01.jpg", "/cars/hyundai-getz-2008/02.jpg", "/cars/hyundai-getz-2008/03.jpg", "/cars/hyundai-getz-2008/04.jpg", "/cars/hyundai-getz-2008/05.jpg", "/cars/hyundai-getz-2008/06.jpg", "/cars/hyundai-getz-2008/07.jpg", "/cars/hyundai-getz-2008/08.jpg", "/cars/hyundai-getz-2008/09.jpg"],
    image: "/cars/hyundai-getz-2008/01.jpg",
  },
  {
    id: "citroen-c4cactus-2017",
    adId: "5829177",
    name: "Citroën C4 Cactus",
    make: "Citroën",
    brandSlug: "citroen",
    model: "C4 Cactus",
    price: 7250,
    year: 2017,
    mileage: 190000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "Hatchback",
    power: "60 kW / 82 hp",
    hp: 82,
    color: "Black",
    euro: "Euro 6",
    registration: "Macedonian, registered until 09.2026",
    rating: 4.4,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS"],
    description:
      "This 2017 Citroën C4 Cactus runs a 1.2-litre petrol engine producing 60 kW / 82 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia, Finished in black, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 6 compliant.",
    images: ["/cars/citroen-c4cactus-2017/01.jpg", "/cars/citroen-c4cactus-2017/02.jpg", "/cars/citroen-c4cactus-2017/03.jpg", "/cars/citroen-c4cactus-2017/04.jpg", "/cars/citroen-c4cactus-2017/05.jpg", "/cars/citroen-c4cactus-2017/06.jpg", "/cars/citroen-c4cactus-2017/07.jpg", "/cars/citroen-c4cactus-2017/08.jpg", "/cars/citroen-c4cactus-2017/09.jpg"],
    image: "/cars/citroen-c4cactus-2017/01.jpg",
  },
  {
    id: "mazda-3-2011",
    adId: "5829189",
    name: "Mazda 3",
    make: "Mazda",
    brandSlug: "mazda",
    model: "3",
    price: 5200,
    year: 2011,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "80 kW / 109 hp",
    hp: 109,
    color: "Grey",
    euro: "Euro 5",
    registration: "Macedonian, registered until 09.2026",
    rating: 4.3,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Fog lights", "Alloy wheels", "Factory CD radio", "Electric windows", "Central locking", "Power steering", "ABS", "6 airbags", "Airbags", "Winter tyres"],
    description:
      "This 2011 Mazda 3 runs a 1.6-litre diesel engine producing 80 kW / 109 hp, paired with a manual gearbox, and has covered 200,000 km. Imported from Slovenia, Finished in grey, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/mazda-3-2011/01.jpg", "/cars/mazda-3-2011/02.jpg", "/cars/mazda-3-2011/03.jpg", "/cars/mazda-3-2011/04.jpg", "/cars/mazda-3-2011/05.jpg", "/cars/mazda-3-2011/06.jpg", "/cars/mazda-3-2011/07.jpg", "/cars/mazda-3-2011/08.jpg", "/cars/mazda-3-2011/09.jpg", "/cars/mazda-3-2011/10.jpg"],
    image: "/cars/mazda-3-2011/01.jpg",
  },
  {
    id: "peugeot-2008-2019",
    adId: "5830032",
    name: "Peugeot 2008",
    make: "Peugeot",
    brandSlug: "peugeot",
    model: "2008",
    price: 8499,
    year: 2019,
    mileage: 160000,
    fuel: "Petrol",
    transmission: "Manual",
    body: "SUV",
    power: "80 kW / 109 hp",
    hp: 109,
    color: "White",
    euro: "Euro 6",
    registration: "Macedonian, registered until 09.2026",
    rating: 4.5,
    features: ["Climate control", "Air conditioning", "Trip computer", "Cruise control", "Parking sensors", "Rear camera", "Alloy wheels", "Full service history", "Electric windows", "Central locking", "Power steering", "Two keys", "ABS", "8 airbags", "Airbags", "Tow bar"],
    description:
      "This 2019 Peugeot 2008 runs a 1.2-litre petrol engine producing 80 kW / 109 hp, paired with a manual gearbox, and has covered 160,000 km with full service history. Imported from Slovenia, Finished in white, it's presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 6 compliant.",
    images: ["/cars/peugeot-2008-2019/01.jpg", "/cars/peugeot-2008-2019/02.jpg", "/cars/peugeot-2008-2019/03.jpg", "/cars/peugeot-2008-2019/04.jpg", "/cars/peugeot-2008-2019/05.jpg", "/cars/peugeot-2008-2019/06.jpg", "/cars/peugeot-2008-2019/07.jpg", "/cars/peugeot-2008-2019/08.jpg", "/cars/peugeot-2008-2019/09.jpg"],
    image: "/cars/peugeot-2008-2019/01.jpg",
  },
  {
    id: "citroen-c3-2011",
    adId: "5837482",
    name: "Citroën C3",
    make: "Citroën",
    brandSlug: "citroen",
    model: "C3",
    price: 5200,
    year: 2011,
    mileage: 190000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "Hatchback",
    power: "66 kW / 90 hp",
    hp: 90,
    color: "Red",
    euro: "Euro 5",
    registration: "Macedonian, registered until 09.2026",
    rating: 4.3,
    features: ["Climate control", "Cruise control", "Trip computer", "Panoramic roof", "Alloy wheels", "Fog lights", "Power steering", "ABS", "Electric windows", "Central locking", "Two keys", "6 airbags", "Factory CD radio"],
    description:
      "This 2011 Citroën C3 runs a 1.6-litre diesel engine producing 66 kW / 90 hp, paired with a manual gearbox, and has covered 190,000 km with full service history. Imported from Slovenia and finished in red, it features a panoramic roof and is presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 5 compliant.",
    images: ["/cars/citroen-c3-2011/01.jpg", "/cars/citroen-c3-2011/02.jpg", "/cars/citroen-c3-2011/03.jpg", "/cars/citroen-c3-2011/04.jpg", "/cars/citroen-c3-2011/05.jpg", "/cars/citroen-c3-2011/06.jpg", "/cars/citroen-c3-2011/07.jpg", "/cars/citroen-c3-2011/08.jpg", "/cars/citroen-c3-2011/09.jpg"],
    image: "/cars/citroen-c3-2011/01.jpg",
  },
  {
    id: "suzuki-sx4-2010",
    adId: "5837621",
    name: "Suzuki SX4",
    make: "Suzuki",
    brandSlug: "suzuki",
    model: "SX4",
    price: 5200,
    year: 2010,
    mileage: 200000,
    fuel: "Diesel",
    transmission: "Manual",
    body: "SUV",
    power: "66 kW / 90 hp",
    hp: 90,
    color: "Black",
    euro: "Euro 4",
    registration: "Macedonian, registered until 09.2026",
    rating: 4.2,
    features: ["Air conditioning", "Trip computer", "Alloy wheels", "Power steering", "ABS", "Electric windows", "Central locking", "Two keys", "6 airbags", "Pioneer Android radio"],
    description:
      "This 2010 Suzuki SX4 runs a 1.6-litre diesel engine producing 66 kW / 90 hp, paired with a manual gearbox, and has covered 200,000 km with full service history. Imported from Slovenia and finished in black, it is presented in excellent mechanical and technical condition — engine, body and interior all like new — with complete documentation prepared and ready for registration. Euro 4 compliant.",
    images: ["/cars/suzuki-sx4-2010/01.jpg", "/cars/suzuki-sx4-2010/02.jpg", "/cars/suzuki-sx4-2010/03.jpg", "/cars/suzuki-sx4-2010/04.jpg", "/cars/suzuki-sx4-2010/05.jpg", "/cars/suzuki-sx4-2010/06.jpg", "/cars/suzuki-sx4-2010/07.jpg", "/cars/suzuki-sx4-2010/08.jpg", "/cars/suzuki-sx4-2010/09.jpg"],
    image: "/cars/suzuki-sx4-2010/01.jpg",
  }
];

// Distinct brand slugs actually present in stock, ordered by inventory count.
export function brandsInStock(): { slug: string; name: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const c of CARS) counts.set(c.brandSlug, (counts.get(c.brandSlug) ?? 0) + 1);
  return [...counts.entries()]
    .map(([slug, count]) => ({ slug, name: BRAND_META[slug]?.name ?? slug, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}

export function getCar(id: string): Car | undefined {
  return CARS.find((c) => c.id === id);
}

// Up to `n` other cars to suggest — same brand first, then same body, then fill.
export function relatedCars(car: Car, n = 3): Car[] {
  const others = CARS.filter((c) => c.id !== car.id);
  const score = (c: Car) =>
    (c.brandSlug === car.brandSlug ? 2 : 0) + (c.body === car.body ? 1 : 0);
  return [...others].sort((a, b) => score(b) - score(a) || b.year - a.year).slice(0, n);
}

export const PRICE_MIN = Math.min(...CARS.map((c) => c.price));
export const PRICE_MAX = Math.max(...CARS.map((c) => c.price));
export const YEAR_MIN = Math.min(...CARS.map((c) => c.year));
export const YEAR_MAX = Math.max(...CARS.map((c) => c.year));
